### ISSUE TITLE
how to customize look and feel

### ISSUE THREAD

**Issue by subrat7** [avivharuzi/ngx-glide#10]
How to customize the following things

1. How to add images in place of the left arrow and right arrow
2. initially left arrow will be hidden and click on the right arrow left arrow will be visible

**Comment by avivharuzi** [comment]
1. I added support for this kind of thing:

```html
<ngx-glide ... [arrowLeftTemplate]="arrowLeftTemplate" [arrowRightTemplate]="arrowRightTemplate">...</ngx-glide>

<ng-template #arrowLeftTemplate>
  <div class="custom-arrow custom-arrow-left">
    <button mat-raised-button color="accent">👈 CUSTOM LEFT</button>
  </div>
</ng-template>

<ng-template #arrowRightTemplate>
  <div class="custom-arrow custom-arrow-right">
    <button mat-raised-button color="accent">CUSTOM RIGHT 👉</button>
  </div>
</ng-template>
```

```scss
.custom-arrow {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);

  &.custom-arrow-left {
    left: 2.5%;
  }

  &.custom-arrow-right {
    right: 2.5%;
  }
}
```

2. Currently, there is no support for this the idea of this package is to act like a carousel which is infinite
